### ISSUE TITLE
data and code?

### ISSUE THREAD

**Issue by shaoniana1997** [styfeng/SAPPHIRE#1]
Hello, thank you for your nice job! 
When will you release and clean your code? thank you very much -)

**Comment by shaoniana1997** [comment]
I think this job is very beneficial to many downstream works, so can you spare some of your spare time to make the code be public and clean it? Thank you very much -)

**Comment by styfeng** [comment]
Thanks for your interest. We are hoping to release the code by the end of May. Will keep you updated.

**Comment by styfeng** [comment]
update: code + data will be released in the next couple of months... sorry for the massive delays.
